comments_service/api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import PostViewSet, CommentViewSet


app_name='post_api'

router = DefaultRouter()

router.register('posts', PostViewSet, basename='post')


urlpatterns = [
    path('posts/<slug:slug>/comments/', 
        CommentViewSet.as_view({'get': 'list', 'post': 'create'}), 
        name='post-comment-list'),
    path('posts/<slug:slug>/comments/<int:pk>/', 
        CommentViewSet.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'}), 
        name='post-comment-detail'),
    path('posts/favorites/', PostViewSet.as_view({'get': 'favorite'}), 
        name='post_bookmark'),
    path('posts/favorites/add/', PostViewSet.as_view({'post': 'add_to_favorite'}), 
        name='post_bookmark_add'),
    path('posts/favorites/delete/', 
        PostViewSet.as_view({'post': 'delete_from_favorite'}), 
        name='post_bookmark_delete')
]

urlpatterns += router.urls

comments_service/comments/urls.py
from django.urls import path, include
from comments.views import CommentCreate


app_name='comments'
urlpatterns = [
    path('create_comment/<int:post_id>/', CommentCreate.as_view(), name='create_comment'),
]

comments_service/comments_service/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('comments/', include('comments.urls', namespace='comments')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('api/', include('api.urls', namespace='post_api')),
    path('api-auth/', include('rest_framework.urls'))
]

comments_service/posts/urls.py
''' Пути к постам '''
from django.urls import path
from posts.views import PostList, PostDetail

app_name='posts'
urlpatterns = [
    path('', PostList.as_view(), name='list'),
    path('<slug:slug>/', PostDetail.as_view(), name='detail'),
]

comments_service/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.template.defaultfilters import slugify
from django.urls import reverse

User = get_user_model()

class Post(models.Model):
    """Поля модели Post"""
    author = models.ForeignKey(
        User, 
        on_delete=models.CASCADE,
        related_name="post_set",
        null=True
    )
    title = models.CharField(max_length=150,
                            verbose_name='Название поста')
    slug = models.SlugField(max_length=150,
                            verbose_name='Слаг поста',
                            blank=True)
    body = models.TextField(blank=True,
                            verbose_name='Описание поста')
    date_pub = models.DateTimeField(auto_now_add=True,
                                    verbose_name='Время создания поста')
    favorite = models.ManyToManyField(
        User, 
        related_name="favorite_set",
        blank=True,
        null=True
    )


    def get_absolute_url(self):
        """Путь к одному объекту модели Post"""
        return reverse('posts:detail', kwargs={'slug': self.slug})


    def __str__(self):
        """Отображение название объекта"""
        return self.title

    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

comments_service/posts/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.urls import reverse, reverse_lazy
from posts.models import Post
from comments.models import Comment
from comments.forms import CommentForm


class PostList(ListView):
    """Список объектов модели Post"""
    model = Post
    template_name = 'post_list.html'


    def get_queryset(self):
        return Post.objects.order_by('-date_pub')


class PostDetail(DetailView):
    """
    один объект Post,
    и список комментариев с вложенностью
    и пагинацией
    """
    model = Post
    template_name = 'post_detail.html'
    success_url = reverse_lazy('posts:list')


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        comment_form = CommentForm(user=self.request.user,
                                    post_id=None)
        context['post'] = self.get_object
        context['comment_form'] = comment_form 
        return context

comments_service/posts/templates/post_detail.html
{% extends 'base.html' %}
<div class="container">
    <div class="row">
        <div class="col-6 offset-md-2">
            {% block content %}
                <p>{{ post.title }}</p>
                <p>{{ post.body }}</p>
                <p>{{ post.date_pub }}</p>

                {% for comment in post.comments.all %}
                    {{ comment.content }}
                    {{ comment.timestamp }}
                {% endfor %}
                <div class="mb-4"></div>

                <form action="{% url 'comments:create_comment' post_id=post.pk %}" method="post">
                        {% csrf_token %}
                        {{ comment_form }}
                    <input type="submit" value='Оставить комментарий'>
                </form>
                {% endblock %}
        </div>
    </div>
</div> 

comments_service/posts/templates/post_list.html
{% extends 'base.html' %}
<div class="container">
    <div class="row">
        <div class="col-6 offset-md-2">
            {% block content %}
            <h1 class="mt-3">Posts</h1>
            {% for post in object_list %}
            <div class="card mt-3">
                <div class="card-header">
                    {{ post.date_pub }}
                </div>
                <div class="card-body">
                  <h5 class="card-title">{{ post.title }}</h5>
                  <p class="card-text">{{ post.body }}</p>
                  <a href="{% url 'posts:detail' slug=post.slug %}" class="btn btn-primary">Detail</a>
                </div>
              </div>
              {% endfor %}
            {% endblock %}
        </div>
    </div>
</div> 